/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: false,
  swcMinify: true,
  eslint: {
    ignoreDuringBuilds: true,
  },
  images: {
    unoptimized: true,
  },
  env: {
    WEBSITE_URL: 'https://www.ashapurna.com',
    BASE_API_URL: 'http://65.2.27.45/api/web/',
    ENQUIRY_FORM: 'enquiries',
    CONTACT_US_FORM: 'enquiries/contact',
    PARTNER_SUBJECTS: 'enquiries/subjects',
    INVESTOR_SUBJECTS: 'enquiries/property-types',
    ENQUIRY_SUBJECTS: 'home/properties',
    REFERRAL_FORM: 'enquiries/referral-schema',
    REFERRAL_LOCATIONS: 'enquiries/locations',
    CAREER_DATA: 'career',
    CAREER_FORM: 'career/enquiry',
    CAREER_FORM_RESUME: 'https://devapi.digitaltyari.com/ashapurna/api/upload-career-resume',
    HOME_API: 'home',
    ABOUTUS_API: 'about-us',
    PROJECT_CATEGORY_API: 'project/categories',
    PROJECT_LISTING_API: 'project/listing',
    PROJECT_DETAILS_API: 'project/details',
    COMMON_API: 'common-content',
    JOURNEY_API: 'about-us/our-journies',
    MANAGEMENT_API: 'about-us/management-speak',
    TEAM_API: 'about-us/our-team',
    MEDIA_EVENT_API: 'media-events',
    MEDIA_EVENT_DETAIL_API: 'media-events/details',
    NRICORNER_API: 'about-us/nri-corner',
    INVESTORS_CLUB: 'investor-club',
    NEWSLETTER_API: 'newsletter',
    WHYINVEST_API: 'about-us/why-invest-in-jodhpur',
    CSR_API: 'about-us/csr-social-resposibilities',
    TESTIMONIALS_API: 'testimonials',
    EMICALCULATOR_API: 'emi-calculator',
    BECOMEPARTNER_API: 'become-partner',
    RERA_API: 'rera-disclaimer',
    REFERRAL_API: 'referal-schema',
    PRIVACY_POLICY_API: 'privacy-policy',
    TERMS_CONDITIONS_API: 'terms-condition',
  },
}

module.exports = nextConfig
